version: '3.8'

services:
  ai-friend-backend:
    image: ai-friend-backend:latest
    container_name: ai-friend-backend
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
    env_file:
      - .env
    networks:
      - ai-friend-network

networks:
  ai-friend-network:
    name: ai-friend-network
    driver: bridge