name: interview-agent
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - python-dotenv
    - openai
    - langchain
    - colorlog
    - passlib[bcrypt]
    - bcrypt
    - -r requirements.txt 